import json

from sqlalchemy.orm import Session

from models import BusinessModel

BUSINESSES = [
    {
        "id": "biz-001",
        "name": "Nonna's Kitchen",
        "category": "restaurant",
        "description": "Family-run Italian restaurant serving handmade pasta and wood-fired pizzas since 1998. Known for their legendary Sunday sugo.",
        "address": "1847 Commercial Dr, Vancouver, BC",
        "lat": 49.2693,
        "lng": -123.0694,
        "confidence": 0.92,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop",
        "tags": ["italian", "pasta", "family-owned", "dine-in"],
        "discovered_at": "2026-02-14T08:30:00Z",
    },
    {
        "id": "biz-002",
        "name": "Grind & Bloom Coffee",
        "category": "cafe",
        "description": "Specialty coffee roaster and flower shop hybrid. Single-origin pour-overs alongside seasonal bouquets.",
        "address": "1624 Commercial Dr, Vancouver, BC",
        "lat": 49.2671,
        "lng": -123.0700,
        "confidence": 0.88,
        "source": "both",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=400&h=300&fit=crop",
        "tags": ["coffee", "flowers", "specialty", "cozy"],
        "discovered_at": "2026-01-22T14:15:00Z",
    },
    {
        "id": "biz-003",
        "name": "The Drive Barbershop",
        "category": "salon",
        "description": "Old-school barbershop with a modern twist. Hot towel shaves, craft beer on tap, and vintage chairs.",
        "address": "2012 Commercial Dr, Vancouver, BC",
        "lat": 49.2710,
        "lng": -123.0691,
        "confidence": 0.95,
        "source": "street_view",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&h=300&fit=crop",
        "tags": ["barbershop", "grooming", "traditional", "walk-in"],
        "discovered_at": "2026-01-10T09:00:00Z",
    },
    {
        "id": "biz-004",
        "name": "Masa Bakery",
        "category": "bakery",
        "description": "Japanese-inspired sourdough bakery. Shokupan milk bread, matcha croissants, and miso caramel rolls.",
        "address": "1790 Commercial Dr, Vancouver, BC",
        "lat": 49.2685,
        "lng": -123.0697,
        "confidence": 0.91,
        "source": "social_media",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
        "tags": ["bakery", "japanese", "sourdough", "pastries"],
        "discovered_at": "2026-02-28T07:45:00Z",
    },
    {
        "id": "biz-005",
        "name": "Little Mountain Grocery",
        "category": "grocery",
        "description": "Neighborhood grocery specializing in local and organic produce. Weekly CSA boxes from Fraser Valley farms.",
        "address": "1955 Commercial Dr, Vancouver, BC",
        "lat": 49.2702,
        "lng": -123.0692,
        "confidence": 0.87,
        "source": "street_view",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop",
        "tags": ["organic", "local", "produce", "farm-to-table"],
        "discovered_at": "2026-01-05T11:20:00Z",
    },
    {
        "id": "biz-006",
        "name": "Tito Ernesto Tacos",
        "category": "restaurant",
        "description": "Authentic Oaxacan street tacos from a converted garage. Handmade tortillas, mole negro, and horchata.",
        "address": "1538 Commercial Dr, Vancouver, BC",
        "lat": 49.2658,
        "lng": -123.0705,
        "confidence": 0.78,
        "source": "social_media",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=400&h=300&fit=crop",
        "tags": ["mexican", "tacos", "street-food", "authentic"],
        "discovered_at": "2026-03-01T16:30:00Z",
    },
    {
        "id": "biz-007",
        "name": "Pedal & Spoke",
        "category": "repair",
        "description": "Community bike repair co-op. Fix-it workshops, used parts, and affordable tune-ups by volunteer mechanics.",
        "address": "2105 Commercial Dr, Vancouver, BC",
        "lat": 49.2722,
        "lng": -123.0687,
        "confidence": 0.84,
        "source": "both",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&h=300&fit=crop",
        "tags": ["bikes", "repair", "community", "co-op"],
        "discovered_at": "2026-02-05T13:00:00Z",
    },
    {
        "id": "biz-008",
        "name": "Canvas & Clay Studio",
        "category": "art",
        "description": "Drop-in pottery and painting studio. Open studio nights, kiln-fired ceramics, and weekend workshops for all levels.",
        "address": "1920 Commercial Dr, Vancouver, BC",
        "lat": 49.2698,
        "lng": -123.0693,
        "confidence": 0.90,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&h=300&fit=crop",
        "tags": ["pottery", "painting", "studio", "workshops"],
        "discovered_at": "2026-01-18T10:45:00Z",
    },
    {
        "id": "biz-009",
        "name": "Havana Restaurant",
        "category": "restaurant",
        "description": "Beloved Commercial Drive institution with Latin-inspired brunch, live music nights, and a lush back patio.",
        "address": "1212 Commercial Dr, Vancouver, BC",
        "lat": 49.2650,
        "lng": -123.0710,
        "confidence": 0.97,
        "source": "both",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop",
        "tags": ["latin", "brunch", "live-music", "patio"],
        "discovered_at": "2026-01-02T09:30:00Z",
    },
    {
        "id": "biz-010",
        "name": "Pho Lan",
        "category": "restaurant",
        "description": "No-frills Vietnamese pho house with 24-hour bone broth. Cash only. The real deal since 1985.",
        "address": "2680 E Hastings St, Vancouver, BC",
        "lat": 49.2812,
        "lng": -123.0445,
        "confidence": 0.86,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=400&h=300&fit=crop",
        "tags": ["vietnamese", "pho", "cash-only", "late-night"],
        "discovered_at": "2026-02-10T19:00:00Z",
    },
    {
        "id": "biz-011",
        "name": "Sunrise Produce Market",
        "category": "grocery",
        "description": "Asian grocery with the freshest bok choy, live seafood tanks, and imported snacks you cannot find anywhere else.",
        "address": "2420 E Hastings St, Vancouver, BC",
        "lat": 49.2808,
        "lng": -123.0480,
        "confidence": 0.93,
        "source": "street_view",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=400&h=300&fit=crop",
        "tags": ["asian-grocery", "seafood", "produce", "imported"],
        "discovered_at": "2026-01-08T08:00:00Z",
    },
    {
        "id": "biz-012",
        "name": "Golden Needle Tailoring",
        "category": "repair",
        "description": "Master tailor with 30 years experience. Alterations, custom suits, and vintage garment restoration.",
        "address": "2550 E Hastings St, Vancouver, BC",
        "lat": 49.2810,
        "lng": -123.0460,
        "confidence": 0.81,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&h=300&fit=crop",
        "tags": ["tailor", "alterations", "custom", "vintage"],
        "discovered_at": "2026-02-20T15:30:00Z",
    },
    {
        "id": "biz-013",
        "name": "Hastings Ink Tattoo",
        "category": "art",
        "description": "Award-winning tattoo parlor specializing in Japanese traditional and blackwork. Walk-ins welcome Saturdays.",
        "address": "2330 E Hastings St, Vancouver, BC",
        "lat": 49.2805,
        "lng": -123.0498,
        "confidence": 0.94,
        "source": "both",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1598371839696-5c5bb00bdc28?w=400&h=300&fit=crop",
        "tags": ["tattoo", "japanese", "blackwork", "walk-in"],
        "discovered_at": "2026-01-15T12:00:00Z",
    },
    {
        "id": "biz-014",
        "name": "Jade Palace Dim Sum",
        "category": "restaurant",
        "description": "Weekend dim sum with push carts, just like the old days. Har gow, siu mai, and egg tarts made fresh hourly.",
        "address": "2750 E Hastings St, Vancouver, BC",
        "lat": 49.2818,
        "lng": -123.0420,
        "confidence": 0.89,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=400&h=300&fit=crop",
        "tags": ["dim-sum", "chinese", "traditional", "weekend"],
        "discovered_at": "2026-03-05T08:15:00Z",
    },
    {
        "id": "biz-015",
        "name": "East Side Electronics Repair",
        "category": "repair",
        "description": "Phone and laptop repair shop. Screen replacements in 30 minutes, data recovery, and retro console mods.",
        "address": "2200 E Hastings St, Vancouver, BC",
        "lat": 49.2803,
        "lng": -123.0520,
        "confidence": 0.82,
        "source": "social_media",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d7d293b7?w=400&h=300&fit=crop",
        "tags": ["electronics", "phone-repair", "laptop", "retro"],
        "discovered_at": "2026-02-25T11:45:00Z",
    },
    {
        "id": "biz-016",
        "name": "Cafe Calabria",
        "category": "cafe",
        "description": "Iconic Italian cafe with a towering espresso machine. Strong cortados, cannoli, and old-world charm.",
        "address": "1745 Commercial Dr, Vancouver, BC",
        "lat": 49.2680,
        "lng": -123.0698,
        "confidence": 0.96,
        "source": "both",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=400&h=300&fit=crop",
        "tags": ["italian", "espresso", "classic", "cannoli"],
        "discovered_at": "2026-01-03T07:30:00Z",
    },
    {
        "id": "biz-017",
        "name": "Sew & Sew Vintage",
        "category": "retail",
        "description": "Curated vintage clothing and handmade accessories. 70s denim, silk scarves, and one-of-a-kind finds.",
        "address": "2480 E Hastings St, Vancouver, BC",
        "lat": 49.2809,
        "lng": -123.0470,
        "confidence": 0.85,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop",
        "tags": ["vintage", "clothing", "handmade", "accessories"],
        "discovered_at": "2026-03-10T14:00:00Z",
    },
    {
        "id": "biz-018",
        "name": "Main St Sourdough",
        "category": "bakery",
        "description": "Micro-bakery operating out of a converted Victorian house. Naturally leavened breads, Friday-only cinnamon buns.",
        "address": "3845 Main St, Vancouver, BC",
        "lat": 49.2625,
        "lng": -123.1010,
        "confidence": 0.79,
        "source": "social_media",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=400&h=300&fit=crop",
        "tags": ["sourdough", "artisan", "micro-bakery", "weekend"],
        "discovered_at": "2026-03-08T06:30:00Z",
    },
    {
        "id": "biz-019",
        "name": "Monsoon Hair Studio",
        "category": "salon",
        "description": "Indie hair salon with a focus on creative color and textured cuts. Ammonia-free dyes and plant-based products.",
        "address": "4102 Main St, Vancouver, BC",
        "lat": 49.2642,
        "lng": -123.1015,
        "confidence": 0.91,
        "source": "both",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=400&h=300&fit=crop",
        "tags": ["hair", "creative-color", "eco-friendly", "indie"],
        "discovered_at": "2026-01-20T10:00:00Z",
    },
    {
        "id": "biz-020",
        "name": "Kingsgate Books & Records",
        "category": "retail",
        "description": "Independent bookstore and vinyl record shop. Staff picks, local zines, and listening stations for rare pressings.",
        "address": "4220 Main St, Vancouver, BC",
        "lat": 49.2655,
        "lng": -123.1020,
        "confidence": 0.93,
        "source": "street_view",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1526243741027-444d633d7365?w=400&h=300&fit=crop",
        "tags": ["books", "vinyl", "indie", "local"],
        "discovered_at": "2026-01-12T13:15:00Z",
    },
    {
        "id": "biz-021",
        "name": "Thanh Thanh Banh Mi",
        "category": "restaurant",
        "description": "Hole-in-the-wall banh mi counter. Crispy baguettes, five-spice pork, pickled daikon, and fresh cilantro.",
        "address": "4050 Main St, Vancouver, BC",
        "lat": 49.2638,
        "lng": -123.1013,
        "confidence": 0.76,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1600688640154-9619e002df30?w=400&h=300&fit=crop",
        "tags": ["vietnamese", "banh-mi", "sandwich", "quick-bite"],
        "discovered_at": "2026-03-12T12:00:00Z",
    },
    {
        "id": "biz-022",
        "name": "Roots & Wings Plant Shop",
        "category": "retail",
        "description": "Tropical and rare houseplant shop. Variegated monsteras, custom planters, and plant care workshops.",
        "address": "3920 Main St, Vancouver, BC",
        "lat": 49.2630,
        "lng": -123.1012,
        "confidence": 0.88,
        "source": "social_media",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=300&fit=crop",
        "tags": ["plants", "tropical", "rare", "workshops"],
        "discovered_at": "2026-02-18T09:30:00Z",
    },
    {
        "id": "biz-023",
        "name": "Cartems Donuts",
        "category": "bakery",
        "description": "Artisanal donut shop with rotating seasonal flavors. Earl Grey, whiskey bacon, and vegan options available.",
        "address": "3850 Main St, Vancouver, BC",
        "lat": 49.2627,
        "lng": -123.1011,
        "confidence": 0.95,
        "source": "both",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=300&fit=crop",
        "tags": ["donuts", "artisanal", "vegan", "seasonal"],
        "discovered_at": "2026-01-06T08:00:00Z",
    },
    {
        "id": "biz-024",
        "name": "Uncle Abe Watch Repair",
        "category": "repair",
        "description": "Third-generation watchmaker. Mechanical watch servicing, vintage restoration, and battery replacements.",
        "address": "2600 E Hastings St, Vancouver, BC",
        "lat": 49.2811,
        "lng": -123.0455,
        "confidence": 0.73,
        "source": "street_view",
        "on_google": False,
        "image_url": "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400&h=300&fit=crop",
        "tags": ["watches", "repair", "vintage", "mechanical"],
        "discovered_at": "2026-03-15T14:30:00Z",
    },
    {
        "id": "biz-025",
        "name": "The Laughing Bean",
        "category": "cafe",
        "description": "Community cafe and open mic venue. Fair-trade coffee, vegan baking, and local art on the walls.",
        "address": "2695 Commercial Dr, Vancouver, BC",
        "lat": 49.2748,
        "lng": -123.0680,
        "confidence": 0.90,
        "source": "both",
        "on_google": True,
        "image_url": "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=400&h=300&fit=crop",
        "tags": ["coffee", "open-mic", "vegan", "community"],
        "discovered_at": "2026-01-25T11:00:00Z",
    },
]


def seed_db(db: Session):
    """Seed database with mock businesses if empty."""
    if db.query(BusinessModel).count() > 0:
        return

    for biz in BUSINESSES:
        record = BusinessModel(
            id=biz["id"],
            name=biz["name"],
            category=biz["category"],
            description=biz["description"],
            address=biz["address"],
            lat=biz["lat"],
            lng=biz["lng"],
            confidence=biz["confidence"],
            source=biz["source"],
            on_google=biz["on_google"],
            image_url=biz["image_url"],
            tags=json.dumps(biz["tags"]),
            discovered_at=biz["discovered_at"],
        )
        db.add(record)

    db.commit()
    print(f"Seeded {len(BUSINESSES)} businesses")
